services:
  - type: web
    name: heimdallr-backend
    env: node
    rootDir: backend
    buildCommand: npm install --include=dev --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CELESTRAK_URL
        value: https://celestrak.com/NORAD/elements/gp.php?GROUP=active&FORMAT=tle
      - key: FRONTEND_URL
        value: https://heimdallrproject.vercel.app
      - key: OPENSKY_USERNAME
        value: n3on250-api-client
      - key: OPENSKY_PASSWORD
        value: VJoEq5HThldIpB1IP2Yy6zLQzJL0jCEN
